### PR TITLE
Create FP_E2V_2s_l3cp_v28_Nop.seq

### PR DESCRIPTION
**Pull request by antilogus**
Add the ClearNop [main] (and associated subroutine and function ) for a Clear that hopefully will not fill pocket at the image/serial register interface when clearing saturated image

### CODE REVIEW

**Review by cjuramy — COMMENTED** [review]
I think it would make more sense to replace the function and keep the subroutines as they are, rather than adding more unused stuff to the sequencer file.

**Comment by antilogus** [comment]
You are right , this also will make the usage of this sequencer much easier ( nothing else to change except the sequencer itself ) . So I did the change , and also produced the ITL version in this pull request

**Review by cjuramy — COMMENTED** [review]
Looks good to me now.

**Comment by youtsumi** [comment]
Ok, I see the below is the only meaningful change and looks good to me


```
(miniforge3-23.3.1-1/envs/np_veclib) yutsumi@kailua run7 % diff  FP_ITL_2s_l3cp_v28.seq FP_ITL_2s_l3cp_v28_Nop.seq 
24a25
>     BufferSE2V:       80 ns   # Buffer for serial clock crossing (mach e2v time)
111,112c112,115
<     ParallelFlush: # Single line transfer with all serial register clocks high to flush it
<       clocks:          P1, P2, P3
---
> 
> 
>     ParallelFlush: # One line transfer with serial clocks high to flush it
>       clocks:          P1, P2, P3, S3
114,120c117,125
<          FlushP      = 0,  1,  0   # +5000 =  5000
<          FlushP      = 0,  1,  1   # +5000 = 10000
<          FlushP      = 0,  0,  1   # +5000 = 15000
<          FlushP      = 1,  0,  1   # +5000 = 20000
<          FlushP      = 1,  0,  0   # +5000 = 25000
<          FlushP      = 1,  1,  0   # +5000 = 30000
<       constants: S1=1, S2=1, S3=1, RG=1, RST=1
---
>          FlushP      = 0,  1,  0 , 1  # +5000 =  5000
>          BufferSE2V  = 0,  1,  0 , 0  # +  80 =  5080
>          FlushP      = 0,  1,  1 , 0  # +5000 = 10080
>          FlushP      = 0,  0,  1 , 0  # +5000 = 15080
>          FlushP      = 1,  0,  1 , 0  # +5000 = 20080
>          FlushP      = 1,  0,  0 , 0  # +5000 = 25080
>          BufferSE2V  = 1,  0,  0 , 1  # +  80 = 25160
>          FlushP      = 1,  1,  0 , 1  # +5000 = 30160
>       constants: S1=1, S2=1, RG=1, RST=1
121a127
> 
327a334
> 
349a357
> 
(miniforge3-23.3.1-1/envs/np_veclib) yutsumi@kailua run7 % diff  FP_E2V_2s_l3cp_v28.seq FP_E2V_2s_l3cp_v28_Nop.seq 
7a8
>  
117a119
>  
119c121
<       clocks:          P1, P2, P3, P4
---
>       clocks:         P1, P2, P3, P4, S3
121,126c123,131
<          FlushP      = 0,  1,  1,  0  # 6000
<          FlushP      = 0,  0,  1,  1  # 12000
<          FlushP      = 1,  0,  0,  1  # 18000
<          FlushP      = 1,  1,  0,  0  # 24000
<          FlushP      = 0,  1,  1,  0  # 30000
<       constants: S1=1, S2=1, S3=1, RG=1, RST=1
---
>          FlushP      = 0,  1,  1,  0,  1  # 6000
>          BufferS     = 0,  1,  1,  0,  0  # 6080
>          FlushP      = 0,  0,  1,  1,  0  # 12080
>          FlushP      = 1,  0,  0,  1,  0  # 18080
>          FlushP      = 1,  1,  0,  0,  0  # 24080
>          BufferS     = 1,  1,  0,  0,  1  # 24160
>          FlushP      = 0,  1,  1,  0,  1  # 30160
>       constants: S1=1, S2=1, RG=1, RST=1
> 
329a335
> 
351a358
>
```

**Pull request merged**
